### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by jstephendix** [d8-contrib-modules/securepages#4]
When signing in as http and then going to https page - requested page continues to redirect. This also occurs when logging out.

**Comment by nerdstein** [comment]
This is unclear on functional objective, more research is needed between D7 module and D8 requirement

**Comment by jose-oliveira** [comment]
This problem occurs because when you change from http to https the session isn't shared, so the user is redirected to a page like: system/403?destination=admin/config/securepages, causing a loop.
My idea to fix that:
- On checkForHttp method, if $redirect == FALSE and status = 403, don't do the redirect. I tried this one on my dev environment and it works.
- On checkForHttp method, if $redirect == FALSE and the parameter "destination" is set, don't do the redirect. I tried this one on my dev environment and it works.
- Use an exception listener and prevent redirection if status = 403. I'm not sure how to this in D8(or if it's even possible), but sounds like a good to fix that as well.

**Comment by nerdstein** [comment]
Where is the "checkForHttp" method?

Are there any additional conditions at play here? For instance, is this _only_ with the path "admin/config/securepages"? 

What is triggering the transition from HTTP to HTTPS?

**Comment by jose-oliveira** [comment]
It's in the SecurePagesEventSubscriber class.

It happens for any page the user get access denied.
Also, for this to happen, the setting: **"Switch back to http pages when there are no matches to list of pages above. "** must be set to **"Yes"**

The loop work like this:
- User is redirected to https version of ${ADMIN_PAGE}
- User doesn't have permission to access the page, so it's redirected to system/403?destination=/${ADMIN_PAGE}
- Because of the destination parameter, user is redirected again to ${ADMIN_PAGE}, restarting the whole process.

I'm investigating how the destination parameter works on D8 to maybe come up with a better idea to solve that.

**Comment by jose-oliveira** [comment]
After checking how the "destination" parameter works(more info: https://github.com/d8-contrib-modules/securepages/issues/12#issuecomment-139317128), I think this option might be the best one:

"On checkForHttp method, if $redirect == FALSE and the parameter "destination" is set, don't do the redirect. I tried this one on my dev environment and it works."

I created PR #27 with this proposed solution.

**Comment by jstephendix** [comment]
Tested and issue was resolved in PR#27, making as closed.
